### ISSUE TITLE
_b00t_ inclusion

### ISSUE THREAD

**Issue by elasticdotventures** [SkypLabs/bsfl#11]
Hi, I'm working on an development ops/stack called _b00t_
https://github.com/elasticdotventures/_b00t_

I'd like to include BSFL - is that cool?  Just wanted to drop a note and let you know, a bit of overlap.  _b00t_ will ultimately have an FZF menu + well orchestrated bash build environment for containers & idempotent applications.

**Comment by SkypLabs** [comment]
Hi @elasticdotventures,

Of course! BSFL is made for that :)

Thanks for letting me know.

**Comment by SkypLabs** [comment]
I'm closing this issue. Feel free to reopen it if needed.
