### ISSUE TITLE
Typo in the command name?

### ISSUE THREAD

**Issue by espoelstra** [SkypLabs/bsfl#3]
Was hard to tell whether it was supposed to be printing a failure or just silently running the command based on the next example using debug.

https://github.com/SkypLabs/bsfl/blob/cb751c260ad02dda105e28ee106b148c2277a19d/examples/command.sh#L14

**Comment by SkypLabs** [comment]
Hi @espoelstra.

Thank you for your interest in this project.

Actually, it is not a typo, or in other words, it is an on-purpose one used to demonstrate the output of an invalid/failed command.
